const images = ['/Agency-Website-Demo/images/anchor.svg',
                '/Agency-Website-Demo/images/apple-touch-icon.png',
                '/Agency-Website-Demo/images/author-2.jpg',
                '/Agency-Website-Demo/images/author-3.jpg',
                '/Agency-Website-Demo/images/author-4.jpg',
                '/Agency-Website-Demo/images/author.jpg',
                '/Agency-Website-Demo/images/basket.svg',
                '/Agency-Website-Demo/images/blog-hero.jpg',
                '/Agency-Website-Demo/images/bycicle.svg',
                '/Agency-Website-Demo/images/chemestry.svg',
                '/Agency-Website-Demo/images/contact-hero.jpg',
                '/Agency-Website-Demo/images/favicon.png',
                '/Agency-Website-Demo/images/hero.jpg',
                '/Agency-Website-Demo/images/ipad-pro.png',
                '/Agency-Website-Demo/images/map.png',
                '/Agency-Website-Demo/images/microphone.svg',
                '/Agency-Website-Demo/images/paper-plane.svg',
                '/Agency-Website-Demo/images/photo.svg',
                '/Agency-Website-Demo/images/portfolio-1.jpg',
                '/Agency-Website-Demo/images/portfolio-10.jpg',
                '/Agency-Website-Demo/images/portfolio-11.jpg',
                '/Agency-Website-Demo/images/portfolio-12.jpg',
                '/Agency-Website-Demo/images/portfolio-2.jpg',
                '/Agency-Website-Demo/images/portfolio-3.jpg',
                '/Agency-Website-Demo/images/portfolio-4.jpg',
                '/Agency-Website-Demo/images/portfolio-5.jpg',
                '/Agency-Website-Demo/images/portfolio-6.jpg',
                '/Agency-Website-Demo/images/portfolio-7.jpg',
                '/Agency-Website-Demo/images/portfolio-8.jpg',
                '/Agency-Website-Demo/images/portfolio-9.jpg',
                '/Agency-Website-Demo/images/portfolio-hero.jpg',
                '/Agency-Website-Demo/images/rocket.svg'];                

images.forEach((image) => {
  const img = new Image();
  img.src = image;
});